version: '3'
services:
  exercise1:
    build: ./proxyService-messageapp/.
    ports:
      - "9001:9001"
    depends_on:
      - "mongodb"
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "3000:3000"
  mongodb:
    image: "mongo"
    volumes:
      - ./data/db:/data/db
    ports:
      - "28017:28017"